"""Bounded Alembic autogenerate policy for known legacy schema details.

The migration history is authoritative for a small set of PostgreSQL details
that the runtime ORM intentionally does not model 1:1.  Keep every exception
explicit here so ``alembic check`` still reports any *new* mismatch.
"""
from __future__ import annotations

from typing import Any

from sqlalchemy import JSON
from sqlalchemy.dialects.postgresql import JSONB

# Indexes created intentionally by historical migrations but not represented
# in runtime ORM metadata (partial, expression, search, or operational indexes).
# The list also includes a few indexes that metadata now models exactly; the
# include hook only suppresses an entry when it is DB-only (compare_to=None).
_MIGRATION_OWNED_DB_INDEXES = frozenset(
    {
        ("activities", "ix_activities_archived_at"),
        ("activities", "ix_activities_gmail_message_id"),
        ("activities", "ix_activities_lead_type"),
        ("activities", "ix_activities_parent_task_id"),
        ("companies", "idx_companies_domain"),
        ("companies", "idx_companies_name_trgm"),
        ("companies", "idx_companies_normalized"),
        ("companies", "idx_companies_workspace"),
        ("companies", "uq_companies_inn"),
        ("contacts", "idx_contacts_company_id"),
        ("contacts", "idx_contacts_email"),
        ("contacts", "idx_contacts_name_trgm"),
        ("contacts", "idx_contacts_phone"),
        ("contacts", "idx_contacts_workspace"),
        ("custom_attribute_definitions", "uq_custom_attr_def_workspace_key"),
        ("enrichment_runs", "ix_enrichment_runs_lead_started"),
        ("inbox_messages", "ix_inbox_msg_unmatched"),
        ("inbox_messages", "uq_inbox_msg_external"),
        ("lead_custom_values", "uq_lead_custom_value_lead_def"),
        ("leads", "idx_leads_company_id"),
        ("leads", "idx_leads_max_user_id"),
        ("leads", "idx_leads_name_trgm"),
        ("leads", "idx_leads_tg_chat_id"),
        ("leads", "ix_leads_company_name_fts"),
        ("llm_usage", "ix_llm_usage_workspace_created"),
        ("message_templates", "uq_message_templates_workspace_name_channel"),
        ("presence_minutes", "ix_presence_minutes_ws_minute"),
        ("quotas", "ix_quotas_workspace_period"),
        ("user_invites", "ix_user_invites_email"),
        ("user_invites", "ix_user_invites_workspace_email"),
        # Migration 0001 created a separate non-unique lookup index in
        # addition to the users_supabase_user_id_key unique constraint.
        ("users", "ix_users_supabase_user_id"),
    }
)

# Server defaults which exist in migration-built PostgreSQL but are not part
# of the ORM write contract. They are useful for direct SQL / old rows and are
# not candidates for destructive "drop default" autogenerated operations.
_MIGRATION_OWNED_SERVER_DEFAULTS = frozenset(
    {
        ("activities", "payload_json"),
        ("activities", "task_done"),
        ("channel_connections", "status"),
        ("companies", "id"),
        ("companies", "is_archived"),
        ("contacts", "confidence"),
        ("contacts", "verified_status"),
        ("daily_plans", "summary_json"),
        ("enrichment_runs", "duration_ms"),
        ("enrichment_runs", "sources_used"),
        ("enrichment_runs", "status"),
        ("followups", "position"),
        ("followups", "reminder_kind"),
        ("followups", "status"),
        ("inbox_messages", "id"),
        ("ingest_conflicts", "status"),
        ("ingest_jobs", "file_count"),
        ("ingest_jobs", "status"),
        ("lead_sources", "is_active"),
        ("lead_sources", "is_paid"),
        ("lead_sources", "is_system"),
        ("lead_sources", "sort_order"),
        ("lead_stage_history", "id"),
        ("leads", "assignment_status"),
        ("leads", "is_rotting_next_step"),
        ("leads", "is_rotting_stage"),
        ("leads", "score"),
        ("leads", "tags_json"),
        ("llm_usage", "completion_tokens"),
        ("llm_usage", "cost_usd"),
        ("llm_usage", "prompt_tokens"),
        ("pipelines", "position"),
        ("pipelines", "type"),
        ("quotas", "currency"),
        ("scoring_criteria", "max_value"),
        ("service_api_keys", "scopes"),
        ("stages", "color"),
        ("stages", "gate_criteria_json"),
        ("stages", "is_lost"),
        ("stages", "is_won"),
        ("stages", "position"),
        ("stages", "probability"),
        ("stages", "rot_days"),
        ("user_invites", "suggested_role"),
        ("users", "max_active_deals"),
        ("users", "name"),
        ("users", "onboarding_completed"),
        ("users", "role"),
        ("users", "specialization"),
        ("users", "timezone"),
        ("users", "ui_prefs_json"),
        ("users", "working_hours_json"),
        ("utm_campaigns", "is_auto"),
        ("utm_mediums", "is_auto"),
        ("utm_sources", "is_auto"),
        ("workspaces", "plan"),
        ("workspaces", "settings_json"),
        ("workspaces", "sprint_capacity_per_week"),
    }
)

# These six columns are JSONB in PostgreSQL by migration design, while their
# ORM declarations intentionally stay generic JSON for lightweight test-stub
# compatibility. Keep this exception column-scoped.
_JSONB_AS_JSON_COLUMNS = frozenset(
    {
        ("automation_step_runs", "step_json"),
        ("automations", "steps_json"),
        ("leads", "agent_state"),
        ("leads", "score_details_json"),
        ("service_api_keys", "scopes"),
        ("users", "ui_prefs_json"),
    }
)


def _column_key(metadata_column: Any) -> tuple[str | None, str | None]:
    return (
        getattr(getattr(metadata_column, "table", None), "name", None),
        getattr(metadata_column, "name", None),
    )


def include_object(
    object_: Any,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: Any,
) -> bool:
    """Suppress only known migration-owned indexes that exist DB-side only."""
    if type_ == "index" and reflected and compare_to is None:
        table = getattr(getattr(object_, "table", None), "name", None)
        if (table, name) in _MIGRATION_OWNED_DB_INDEXES:
            return False
    return True


def compare_server_default(
    context: Any,
    inspected_column: Any,
    metadata_column: Any,
    inspected_default: Any,
    metadata_default: Any,
    rendered_metadata_default: str | None,
) -> bool | None:
    """Preserve only the known DB defaults that metadata does not own."""
    if (
        _column_key(metadata_column) in _MIGRATION_OWNED_SERVER_DEFAULTS
        and inspected_default is not None
        and metadata_default is None
    ):
        return False
    return None


def compare_type(
    context: Any,
    inspected_column: Any,
    metadata_column: Any,
    inspected_type: Any,
    metadata_type: Any,
) -> bool | None:
    """Treat the six intentional PostgreSQL JSONB / ORM JSON pairs as equal."""
    if (
        _column_key(metadata_column) in _JSONB_AS_JSON_COLUMNS
        and isinstance(inspected_type, JSONB)
        and isinstance(metadata_type, JSON)
        and not isinstance(metadata_type, JSONB)
    ):
        return False
    return None
